### PR TITLE
VGM: Add support for format (preliminary)

### LINKED ISSUE #38: Add support for the VGM file format
There are many songs out there [dumped in the VGM file format for the OPL3](https://vgmrips.net/packs/chip/ymf262). Amongst them are gems like the Cybersphere, Miwaku no Chousho and Puyo Puyo 2 soundtracks.

The VGM file specs are very simple and can be obtained [here](https://vgmrips.net/wiki/VGM_Specification) and [here](http://www.smspower.org/Music/VGMFileFormat).

Of course only the YMF262 and YMF278 chips will be supported by Adplug for VGM.

### PR DESCRIPTION
**Pull request by binarymaster**
Resolve #38

Notes:
- VGZ not supported (require GZip)
- May be some issues with Dual OPL2 mode

Works excellent with Nuked OPL3 emulator.

### CODE REVIEW

**Comment by Malvineous** [comment]
@binarymaster Did you get my e-mail about commit access to the main AdPlug repos?

**Comment by binarymaster** [comment]
@Malvineous Hello!

No, I didn't get it. However I saw invitation into AdPlug group here, and joined.

**Comment by Malvineous** [comment]
Great!  Hopefully now you can commit these PRs directly into the main repo.  Probably no need to merge them (I don't like merge commits if they can be avoided) but now you have access I'll leave it with you :-)

**Comment by binarymaster** [comment]
@Malvineous it seems like I don't have permission to push commits, see screenshot:

image

Also I can't merge my own PRs, it seems related.

**Comment by binarymaster** [comment]
Commited in https://github.com/adplug/adplug/commit/bf0373ca2308086e6d02633f1f9077d34df79deb.

@Malvineous thanks again! :)

**Pull request closed without merging**
