### PR TITLE
Fixes for issue #110

### PR DESCRIPTION
**Pull request by miller-alex**
I just wanted to show some WIP on fixing #110. For now, I've
* added all the fuzzing samples (redundant samples can be removed/disabled later if tests are too slow),
* fixed the crashes in dtm.cpp and cleaned up the file a bit,
* fixed some crashes in a2m.cpp (not finished yet) and did some cleanup/refactoring there.

There's still a lot to do. If somebody wants to help or has comments/suggestions, just add your comments below.

### CODE REVIEW

**Comment by Malvineous** [comment]
I'm happy to merge WIP changes, but it would be nice if we could do it in such a way as the tests don't fail in the master branch, as it makes it difficult to pick up other unrelated failures coming in as PRs.  I guess keeping the failing tests in separate branches and then rebase-merging them onto the master branch, along with the fixes when they are ready, would be a way to achieve this.

@miller-alex If this sounds good to you, let me know and I'll give you commit access to the project so you don't have to open PRs all the time.

**Comment by miller-alex** [comment]
My plan was to incrementally add more commits until all tests from the issue are fixed, and then mark the PR as ready. I'm about to push the remaining fixes for a2.cpp and cff.cpp right now.
I've mixed adding test cases, bug fixes, and code cleanup in a single branch this time because it's simpler to work with. If you want to merge the fixes before everything is complete I could move them to a different branch or disable the failing test cases by commenting them out.

I don't mind creating a few pull requests. That gives you or others the chance to review the changes before they land in master. But if you don't want to review them and want me to push changes in smaller batches you can give me direct access. I'm fine either way.

**Comment by miller-alex** [comment]
All problems I've seen with the test samples from issue 110 are fixed, with the following two exceptions.
* A few files write out of range data to OPL registers. That's an old issue and not really a problem since the high bits are simply discarded, so I haven't looked into it.
* Some protracker-based players allow setting tempo=0, and then getrefresh() returns 0. That's no problem for the tests, but other consumers may run into problems with an infinite update interval. (Sample i-110_010.a2m exhibits this issue.) Maybe this should be addressed, but I'm not sure what's the expected behavior (interestingly, in CmodPlayer::update(), command 18 explicitly checks for zero and sets tempo, command 15 sets tempo only for values >= 50, and command 7 doesn't check at all).

I didn't keep separate branches for test, fixes, and cleanup, but the commits will end up in the same master branch anyway. I don't think it makes sense to split them.

From my side that's it for the current batch of fixes. (I can add a commit for the tempo=0 issue if you tell me how that should be handled.) I know there are more problems in the code base, but those have to wait for another PR. @Malvineous I think you can merge this PR now unless you have some change requests.

**Comment by Malvineous** [comment]
Excellent work, thanks so much!

**Pull request merged**
