### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by SoapGentoo**
* Fix for minor arches on Gentoo
* Fix for building out-of-source

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@Malvineous thanks for merging, would it be possible that you cut a 2.3.1 release so we can update Gentoo without running autoreconf to regenerate the configure script? Thanks!

**Comment by Malvineous** [comment]
I have no problem with an updated release, but I'm a little short on time at the moment.  Any takers?

**Comment by SoapGentoo** [comment]
@Malvineous I would gladly help, but I'm only a contributor

**Comment by Malvineous** [comment]
Hopefully that problem has been fixed then :)

**Pull request merged**
