### PR TITLE
Add fuzzing samples from issues #85 to #102 as new tests

### PR DESCRIPTION
**Pull request by miller-alex**
Add a new test program for testing fuzzing samples. For now it simply tries to load and play test samples, but this can be extended to cover other parts of the code when samples exposing errors there surface. A a test case fails if the test sample leads to a crash or nonzero exit code (i.e., if an attempt to load a file fails by returning false, that's success).
All fuzzing samples provided by @fcambus and @debrouxl in the issues #85 to #102 are added as test cases to the new test program. Some of these seem to be redundant, especially @debrouxl often added a bunch of samples that trigger the same bug, but I added them all for reference. They can be cleaned up later if desired.

### CODE REVIEW

**Comment by miller-alex** [comment]
Oh, I should mention that these tests may need a memory checker to detect all issues (compile with address sanitizer, run with valgrind, or similar). I didn't hook it up for CI or even add the tests to the windows build files.

**Comment by Malvineous** [comment]
This is really good but unfortunately it really slows down the build process because the stress test takes so long to run.  Is there any way it can be sped up?  Maybe running some tests in parallel or something?

**Comment by Malvineous** [comment]
I'm closing this issue because I have merged it into master, but if you are able to speed it up, please open a new PR with your improvements!  Many thanks :)

**Comment by miller-alex** [comment]
Adding lots of test inevitably slows things down, and I've seen a new batch of samples has already been posted in #110, so it will get even worse. A few thoughts about speeding tests up:

* Parallelization helps a bit, but I don't intend to implement a parallel test harness with bells and whistles in stresstest. If you want to go that route, I'd suggest to remove the ability to run all samples from stresstest, making each sample an individual test case, and move that work to the test harness. No need to reinvent the wheel.
* The easiest way to speed tests up is to reduce the number of test samples. I've simply added all samples that were attached to the issues, bit I think a lot of them are redundant. (The most extreme example, #102 has 151 test samples, but I think it affected only 2 or 3 locations and was fixed with a single change.) Redundant samples may be removed or disabled by default.
* If the stresstest is too slow, it can be removed from the default test target and only be run on explicit request. After all, a memory checker is needed to make it really effective. Building everything with ASAN is not what you typically do, and running stresstest with valgrind is even slower. So maybe it's not that interesting to run it by default.

**Pull request closed without merging**
