### PR TITLE
Add player for PIS format (Beni Tracker)

### PR DESCRIPTION
**Pull request by dmitrysmagin**
I've found a replayer for PIS adlib tunes here:
https://github.com/moxy-bc/pisplay
and decided to adapt it for adplug.

It seems that the original author is Jonas Santoso and he even has a github page (https://github.com/santosoj) but for some reason he has deleted pisplay repo and moxy-bc saved a copy.

Tunes are here: https://github.com/moxy-bc/pisplay/tree/master/tunes
Beni Tracker ported to windows (with sources!) is here:
https://github.com/moxy-bc/pisplay/blob/master/unembedded_resources/Revenge.of.Beni.Tracker.WinALL.iNTERNAL-SPP.zip

More links:
http://justsolve.archiveteam.org/wiki/Beni_Tracker_module
Curiously, it notes PIS as being supported by Adplug.

### CODE REVIEW

**Comment by dmitrysmagin** [comment]
Anyone to review?

**Comment by mywave82** [comment]
I might have some during this weekend @dmitrysmagin.

I can give two feedbacks immediately.

1) your branch contains the mid.cpp fixes. You can remove these by using `git rebase --interactive HEAD~3` and remove the two commits for midi, and if the commit history then looks correct, git a `git push -f`

2) Licence. The repository at https://github.com/moxy-bc/pisplay does not contain any overall license/copyright information, but it does contain fmopl.c which is LGPL 2.1

**Comment by dmitrysmagin** [comment]
Eliminated the mid.cpp modification.

As for the license, most probably the author meant Public Domain. Anyway, pisplay is not a commercial product or part of such, the original Beni Tracker is open-source as well (both QuickBasic and FreeBasic versions). 

If there are still concerns, we might try and reach the author and ask his permission to include the code into adplug under LGPL license.

**Comment by mywave82** [comment]
I cleaned up your commit history, so that it only contains the PIS stuff. There are some few more TODOs:
 [ ] - Loop is not detected at the moment, make it impossible to implement testing (make check)
 [ ] - Add entry into playertest.c and testref/ (see above)

**Comment by dmitrysmagin** [comment]
Yes, currently the tune loops forever, and it should stop and signal that, will fix.
Thanks for the check hint, but I'd have to resolve the absence of "sys/wait.h" on windows in stresstest.cpp

**Comment by dmitrysmagin** [comment]
> I cleaned up your commit history, so that it only contains the PIS stuff. There are some few more TODOs:
> 
>     * [ ]  Loop is not detected at the moment, make it impossible to implement testing (make check)
> 
>     * [ ]  Add entry into playertest.c and testref/ (see above)

Fixed both issues.

**Comment by santosoj** [comment]
> If there are still concerns, we might try and reach the author and ask his permission to include the code into adplug under LGPL license.

Hello. I am the author. It's fine, thanks for your efforts, I'm happy for the PIS format to be included. The original repo is public again at https://github.com/klubderkluebe/pisplay/.

**Comment by dmitrysmagin** [comment]
@santosoj Thanks, this is great!

**Comment by mywave82** [comment]
> Weird, the pipeline for 'make check' fails (see below) with the error:
> 
> ```
> 2023-04-10T08:06:11.7159732Z Error loading: ../../test/testmus/ACTION.PIS
> 2023-04-10T08:06:11.7160004Z FAIL test/playertest (exit status: 1)
> ```
> 
> However, the file name has the correct register. I've re-tested this in linux mint 21.1 and this test passes, the file is read correctly.

I did a local test that works OK. I have added a minor commit to yours, so the hash should change, to see if there are any wierd caching issues. But at the moment the CI seems to get stuck with package cache not being in sync with the repo. Will retry the CI later to see if the problem has gone away

**Pull request merged**
